# -*- coding: utf-8 -*-
"""n-1-demo.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15rdrypFfvGYVIsY_e2Nb_CvHKouVguY7
"""

import streamlit as st
import pandas as pd

st.title("N-1 Contingency: Supply Chain Logistics")
st.write("Adjust the sliders to see how losing one truck affects the ability to meet demand.")

# Sliders for parameters
n_trucks = st.slider("Number of Trucks (N)", min_value=2, max_value=20, value=5)
capacity = st.slider("Capacity per Truck (C)", min_value=10, max_value=100, value=50)
demand = st.slider("Total Daily Demand (D)", min_value=10, max_value=1000, value=180)

# Mathematical calculations
normal_capacity = n_trucks * capacity
n_minus_1_capacity = (n_trucks - 1) * capacity

st.header("The Math")
st.write(f"Normal Capacity: {n_trucks} trucks * {capacity} units = {normal_capacity} units")
st.write(f"N-1 Capacity: ({n_trucks} - 1) trucks * {capacity} units = {n_minus_1_capacity} units")

# Conditional logic for N-1 status
if n_minus_1_capacity >= demand:
    st.success(f"PASS: The remaining {n_trucks - 1} trucks can carry the {demand} units of demand.")
else:
    deficit = demand - n_minus_1_capacity
    st.error(f"FAIL: The remaining {n_trucks - 1} trucks fall short. You will fail to deliver {deficit} units.")

# Visual Representation
st.header("Visual Representation")
chart_data = pd.DataFrame(
    {
        "Units": [demand, normal_capacity, n_minus_1_capacity]
    },
    index=["1. Total Demand", "2. Normal Capacity", "3. N-1 Capacity"]
)

st.bar_chart(chart_data)
