name: Keep Streamlit Awake
on:
  schedule:
    - cron: '0 */10 * * *'
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Empty Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit --allow-empty -m "Keepalive: Prevent Streamlit Sleep"
          git push
